# fly.toml app configuration file generated for taller-dawn-log-7412 on 2024-10-05T01:07:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taller-dawn-log-7412'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
